### ISSUE TITLE
latest release not functional

### ISSUE THREAD

**Issue by chrisgrieser** [maxwelljordanwhite/search-pacmax#2]
Hey, love pacmax! I stumbled upon this, and tried the workflow out. however, it seems like there is something amiss with the workflow. the keywords result in an error page and they actually only lead to an URL-opening searches: `https://pacmax.org/wp-json/wp/v2/{pac}?search={query}`

which is weird, as the workflow-file contains quite a few python scripts. Maybe you uploaded a wrong file?

**Comment by gitatmax** [comment]
Hey @chrisgrieser, sorry for the holdup here & thanks for bringing this to my attention. I'm not exactly sure what caused the issue then, but I think it may be moot now that I've overhauled the site's search functionality.

The search query would look something like `https://pacmax.org/?s={query}`; I'm pushing an updated & working version here shortly, if you're interested.

By the way, I'm thrilled you dig the site :)

**Comment by chrisgrieser** [comment]
yep, got it, works, thanks!
