### ISSUE TITLE
search on main website doesn’t work

### ISSUE THREAD

**Issue by andrewcrook** [maxwelljordanwhite/search-pacmax#3]
Tried on Safari 15

**Comment by gitatmax** [comment]
Hey @andrewcrook, thank you for the heads-up and for your patience here. I've made some significant changes to the site's search recently; I gave it a go in Safari 15.4, and it seems to be working okay for me. Are you still experiencing issues, though?

**Comment by gitatmax** [comment]
Hey @andrewcrook, thank you for the heads-up and for your patience here. I've made some significant changes to the site's search recently; I gave it a go in Safari 15.4, and it seems to be working okay for me. Are you still experiencing issues, though?

**Comment by gitatmax** [comment]
I'm going to close this, but please don't hesitate to reopening it if you're still facing issues searching :)

**Comment by andrewcrook** [comment]
> I'm going to close this, but please don't hesitate to reopening it if you're still facing issues searching :)

Sorry for the delay, I tested this morning and it is working of Safari 15. Thank you.

**Comment by gitatmax** [comment]
@andrewcrook No problem! Thanks for confirming- I'm glad it's working again.
